version: '3.4'
services:
  liferay:
    container_name: "liferay"
    image: "liferay/portal:7.2.1-ga2"
    depends_on:
      - mysql_liferay
    volumes:
      - "./docker/deploy:/mnt/liferay/deploy"
      - "./docker/osgi/modules:/mnt/liferay/osgi/modules"
      - "./docker/files:/mnt/liferay/files"
    ports:
      - "8080:8080"
      - "9000:9000"
      - "8000:8000"
      - "11311:11311"
    environment:
      - "JAVA_OPTS=-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n"
    networks:
      - lfrnet
  mysql_liferay:
    container_name: "mysql_liferay"
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    volumes:
      - "my-db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lportal
      MYSQL_USER: lportal
      MYSQL_PASSWORD: lportal
    networks:
      - lfrnet
    command: ['mysqld', "--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
  redis:
    container_name: "redis"
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lfrnet

networks:
  lfrnet:

volumes:
    my-db: